version = 0.1
[default.deploy.parameters]
stack_name = "sam-cloudwatch-retention-period-setter"
resolve_s3 = true
s3_prefix = "sam-cloudwatch-retention-period-setter"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
