AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  See: https://github.com/jecc1982/amazon-sam-cloudwatch-retention-period-setter
  This template deploys a Lambda function that is triggered everyday to set any CloudWatch log group that does not have retention period set.
Parameters:  
  Retention: 
    Description: >
      The number of days you would like to retain your logs in CloudWatch log groups.
      Possible values for this variable:1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 2192, 2557, 2922, 3288, and 3653
    Type: Number
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 2192
      - 2557
      - 2922
      - 3288
      - 3653
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
Resources:
  LambdaPermissionsToCW:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Join ['-', ['LambdaExecutionRolePolicyCW', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutRetentionPolicy
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                Resource: "*"
  CWRetentionPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: retention_period_setter/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaPermissionsToCW.Arn
      Runtime: python3.9
      Environment:
        Variables:
          RETENTION_DAYS: !Ref Retention
      Events:
        RunDaily:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 day)'
      
        